Gaijinizer patch/CommonEvents_180.txt
Gaijinizer patch/CommonEvents_202.txt
Gaijinizer patch/CommonEvents_207.txt
Gaijinizer patch/CommonEvents_440.txt
Gaijinizer patch/Map050.txt
Gaijinizer patch/Map055.txt
Gaijinizer patch/Skills.txt
Gaijinizer patch/Troops.txt

- Minor tidy up of some misc lines.
- Manual translation of one of the missed endings for Mother Rabbit's encounter.
- Polish off of some Tanuki lines.

Chapter 2-1 cleanup

---

Gaijinizer patch/CommonEvents_173.txt
Gaijinizer patch/CommonEvents_211.txt
Gaijinizer patch/CommonEvents_212.txt
Gaijinizer patch/CommonEvents_264.txt
Gaijinizer patch/CommonEvents_294.txt
Gaijinizer patch/Map041.txt
Gaijinizer patch/Map080.txt
Gaijinizer patch/Troops.txt

All of Mukuro's My Room dialogue should be complete except for the engagement scenes.
There may be a conflict once the 2-2 PR is merged as some scenes reused dialogue from there.

Mukuro - My Room

---

Gaijinizer patch/CommonEvents_173.txt
Gaijinizer patch/Map019.txt
Gaijinizer patch/Map027.txt
Gaijinizer patch/Map041.txt
Gaijinizer patch/Map042.txt
Gaijinizer patch/Map062.txt

Tidying up the missed gift dialogue in some old My Room translations.

My room minor cleanups

---

Gaijinizer patch/CommonEvents_3.txt
Gaijinizer patch/Map080.txt
Gaijinizer patch/Skills.txt

Fixed a crash bug on Mukuro cleansing corruption, and a few minor things.

Quick patch, and fixed a missed file from EX2

---

Gaijinizer patch/CommonEvents_239.txt
Gaijinizer patch/Map002.txt
Gaijinizer patch/Map030.txt
Gaijinizer patch/Map066.txt
Gaijinizer patch/Map067.txt
Gaijinizer patch/Map081.txt
Gaijinizer patch/Map082.txt
Gaijinizer patch/Map096.txt
Gaijinizer patch/Map097.txt
Gaijinizer patch/Map118.txt

Fixed some messed up line spacing pre-style guide, cleaned up some logistic stuff for Chapter 3-1.

Minor Ch2-2/3-1 fixes

---

Gaijinizer patch/Enemies.txt

Ending tags are broken in Gaijinizer. For now add them manually, and clean up the text for Lampas and Barghest.

Add Hotfix for Compendium

---

Gaijinizer patch/Enemies.txt

Fixing typos and capitalisations.

Compendium fixes for Barghest and Lampas.

---

Gaijinizer patch/CommonEvents_172.txt
Gaijinizer patch/CommonEvents_173.txt
Gaijinizer patch/CommonEvents_313.txt
Gaijinizer patch/CommonEvents_344.txt
Gaijinizer patch/Enemies.txt
Gaijinizer patch/Map003.txt
Gaijinizer patch/Map120.txt
Gaijinizer patch/Troops.txt

- All of Sphinx's My Room dialogue (including engagement)
- Cushion's Sphinx battle advice
- All of Sphinx's compendium entries

Sphinx My Room and Compendium

---

Gaijinizer patch/Map002.txt
Gaijinizer patch/Map003.txt
Gaijinizer patch/Map014.txt

Clean up some scene hints, and a bit of Chapter 1-2.

Clean up Scene Hints

---

Gaijinizer patch/Actors.txt
Gaijinizer patch/Armors.txt
Gaijinizer patch/Classes.txt
Gaijinizer patch/Enemies.txt
Gaijinizer patch/Map002.txt
Gaijinizer patch/MapInfos.txt
Gaijinizer patch/Skills.txt
Gaijinizer patch/Troops.txt

Cleanup all of the changed lines for the base game in Ver 7.0. Added new lines to Troops and Skills.

Ver 7.00 Cleanup

---

Gaijinizer patch/CommonEvents_671.txt
Gaijinizer patch/CommonEvents_673.txt
Gaijinizer patch/CommonEvents_676.txt
Gaijinizer patch/CommonEvents_699.txt
Gaijinizer patch/Map207.txt
Gaijinizer patch/Map377.txt
Gaijinizer patch/Map382.txt
Gaijinizer patch/Map383.txt
Gaijinizer patch/Map384.txt
Gaijinizer patch/Map385.txt
Gaijinizer patch/Skills.txt
Gaijinizer patch/Troops.txt

Haven't finished some of the narration dialogue, but this is a good first chunk.

Start working on the initial scenes of EX3

---

Gaijinizer patch/CommonEvents_172.txt
Gaijinizer patch/CommonEvents_173.txt
Gaijinizer patch/CommonEvents_289.txt
Gaijinizer patch/CommonEvents_294.txt
Gaijinizer patch/CommonEvents_369.txt
Gaijinizer patch/Enemies.txt
Gaijinizer patch/Map119.txt
Gaijinizer patch/Troops.txt

* Archeny chat dialogue
* Archeny bonding dialogue
* Archeny engagement dialogue
* Archeny compendium entries
* Archeny gift dialogue
* Archeny battle advice
* Aconitum compendium entires
* Archeny and Aconitum milking scenes

Archeny my room and comp

---

Gaijinizer patch/CommonEvents_172.txt
Gaijinizer patch/CommonEvents_173.txt
Gaijinizer patch/CommonEvents_452.txt
Gaijinizer patch/CommonEvents_454.txt
Gaijinizer patch/CommonEvents_543.txt
Gaijinizer patch/Enemies.txt
Gaijinizer patch/Map002.txt
Gaijinizer patch/Map215.txt
Gaijinizer patch/Troops.txt

* All My Room chat dialogue except engagement reviewed
* All H-scene dialogue reviewed
* Bonding scene reviewed
* All Camazotz compendium entries translated

Camazotz my room and comp

---

Gaijinizer patch/Armors.txt
Gaijinizer patch/CommonEvents_474.txt
Gaijinizer patch/CommonEvents_482.txt
Gaijinizer patch/CommonEvents_524.txt
Gaijinizer patch/CommonEvents_525.txt
Gaijinizer patch/CommonEvents_527.txt
Gaijinizer patch/Map003.txt
Gaijinizer patch/Map006.txt
Gaijinizer patch/Map176.txt
Gaijinizer patch/Map177.txt
Gaijinizer patch/Map189.txt
Gaijinizer patch/Map193.txt
Gaijinizer patch/Map200.txt
Gaijinizer patch/Map207.txt
Gaijinizer patch/Map208.txt
Gaijinizer patch/Map209.txt
Gaijinizer patch/Map210.txt
Gaijinizer patch/Map211.txt
Gaijinizer patch/Map212.txt
Gaijinizer patch/Map213.txt
Gaijinizer patch/Map214.txt
Gaijinizer patch/Scripts.txt
Gaijinizer patch/Troops.txt

Completed in this PR
- Dialogue during Daiji's phase 2 battle
- Dialogue after sparing Daiji leading up to 4-3
- Dialogue after shooting Daiji
- Neutral Ending A
- Neutral Ending B
- Neutral Ending C
- Ending summary text
- Email 004
- EX crystal requirements
- Dialogue after not taking the shot when you have the chance during the battle
- Wind attack after temptation dialogue
- Cushion's Daiji battle advice
- A few minor typos I found elsewhere #Triketos

Daiji boss battle phase 2

---

Gaijinizer patch/Scripts.txt

Some double quotes in the scripts file were causing a crash. Changed them to single quotes to resolve the issue.

Removed double quotes to stop crash on start.

---

Gaijinizer patch/Armors.txt
Gaijinizer patch/CommonEvents_173.txt
Gaijinizer patch/CommonEvents_471.txt
Gaijinizer patch/CommonEvents_544.txt
Gaijinizer patch/Enemies.txt
Gaijinizer patch/Map019.txt
Gaijinizer patch/Map216.txt
Gaijinizer patch/Troops.txt

- Daji's chat dialogue mostly translated (with a few CheckLaters to review)
- Daji's My Room H scenes all translated
- Daji's compendium entries all translated
- Daji's miscellaneous My Room dialogue (presents, corruption, etc) translated
- A miscellaneous fix here and there

Daji My Room And Compendium

---

Gaijinizer patch/CommonEvents_173.txt
Gaijinizer patch/CommonEvents_211.txt
Gaijinizer patch/CommonEvents_267.txt
Gaijinizer patch/CommonEvents_406.txt
Gaijinizer patch/CommonEvents_543.txt
Gaijinizer patch/CommonEvents_544.txt
Gaijinizer patch/Map019.txt
Gaijinizer patch/Map062.txt
Gaijinizer patch/Map070.txt
Gaijinizer patch/Map080.txt
Gaijinizer patch/Map085.txt
Gaijinizer patch/Map119.txt
Gaijinizer patch/Map120.txt
Gaijinizer patch/Map121.txt
Gaijinizer patch/Map122.txt
Gaijinizer patch/Map215.txt
Gaijinizer patch/Map216.txt
Gaijinizer patch/Map217.txt
Gaijinizer patch/Troops.txt

* Added current friendship values to every My Room
* Finished off Nina's bonding event
* Replaced the 【】 with [] for all the bonding options
* Some minor translation improvements for consistency and style
The variable numbers should all be correct but would probably pay to sanity check them before approving the PR.

Misc cleanup

---

Gaijinizer patch/Armors.txt
Gaijinizer patch/CommonEvents_223.txt
Gaijinizer patch/CommonEvents_278.txt
Gaijinizer patch/Items.txt
Gaijinizer patch/Map003.txt
Gaijinizer patch/Map067.txt
Gaijinizer patch/Map081.txt
Gaijinizer patch/Map106.txt
Gaijinizer patch/Map107.txt
Gaijinizer patch/Skills.txt
Gaijinizer patch/Troops.txt
Gaijinizer patch/Weapons.txt

* Nina boss battle
* Echo dialogue
* Some item and translation clean-ups
Not much needed as some of it had already been done in previous PRs.

Geno 2-3 and 3-1

---

Gaijinizer patch/Map218.txt

All of Reina's three chat options are translated.

Fate's Origin

---

Gaijinizer patch/CommonEvents_184.txt
Gaijinizer patch/CommonEvents_94.txt
Gaijinizer patch/Map003.txt
Gaijinizer patch/Map005.txt
Gaijinizer patch/Map011.txt
Gaijinizer patch/Map013.txt
Gaijinizer patch/Map016.txt
Gaijinizer patch/Map033.txt
Gaijinizer patch/Map050.txt
Gaijinizer patch/Map066.txt
Gaijinizer patch/Map097.txt
Gaijinizer patch/Map102.txt
Gaijinizer patch/Map107.txt
Gaijinizer patch/Troops.txt

With this PR, the clean, TM, and hypocrite geno routes should be done up to the end of chapter 3. There may be some extra bits of dialogue for a second geno run lurking somewhere.

TM geno and hypocrite catch-up

---

Gaijinizer patch/CommonEvents_180.txt
Gaijinizer patch/CommonEvents_228.txt
Gaijinizer patch/CommonEvents_474.txt
Gaijinizer patch/Map003.txt
Gaijinizer patch/Map054.txt
Gaijinizer patch/Map122.txt
Gaijinizer patch/Map132.txt
Gaijinizer patch/Skills.txt
Gaijinizer patch/Troops.txt

- Fixed typos
- Restructured lines that overflowed in-game
- Translated struggle outcomes against Daji's first form

Typos + Daji Struggle

---

Gaijinizer patch/CommonEvents_128.txt
Gaijinizer patch/CommonEvents_290.txt
Gaijinizer patch/CommonEvents_87.txt
Gaijinizer patch/CommonEvents_91.txt
Gaijinizer patch/Map003.txt
Gaijinizer patch/Map027.txt
Gaijinizer patch/Map129.txt
Gaijinizer patch/Map165.txt

Translated a missed line in Lampas' dream fight, all of Titanoboa's battle advice, and the line for the vore filter

Missed Translations

---

Gaijinizer patch/Armors.txt
Gaijinizer patch/CommonEvents_575.txt
Gaijinizer patch/Items.txt
Gaijinizer patch/Map003.txt
Gaijinizer patch/Map134.txt
Gaijinizer patch/Map151.txt
Gaijinizer patch/Map152.txt
Gaijinizer patch/Map153.txt
Gaijinizer patch/Map156.txt
Gaijinizer patch/Map172.txt
Gaijinizer patch/Map251.txt
Gaijinizer patch/Map252.txt
Gaijinizer patch/Map253.txt
Gaijinizer patch/Map270.txt
Gaijinizer patch/Map271.txt
Gaijinizer patch/Map272.txt
Gaijinizer patch/Map276.txt
Gaijinizer patch/Troops.txt
Gaijinizer patch/Weapons.txt

- TM geno 4-1 and 4-2 translated
- Clean geno 4-1 and 4-2 translated
- Hypocrite 4-1 and 4-2 **_probably_** translated
- Some miscellaneous clean-ups done here and there

4-1 and 4-2 geno

---

Gaijinizer patch/CommonEvents_102.txt
Gaijinizer patch/CommonEvents_180.txt
Gaijinizer patch/CommonEvents_24.txt
Gaijinizer patch/CommonEvents_272.txt
Gaijinizer patch/CommonEvents_275.txt
Gaijinizer patch/CommonEvents_428.txt
Gaijinizer patch/CommonEvents_561.txt
Gaijinizer patch/Skills.txt

Barghest, Lampas, Empuse, Mother Rabbit, Mukuro, Echo, Aconitum, Arachne, Camazotz

Persuade outcomes

---

Gaijinizer patch/CommonEvents_166.txt

This file is updated by 7.12, and was horribly out of date. This refactors it with Ron's translation.

Common_Events 166 Refactor

---

Gaijinizer patch/Enemies.txt
Gaijinizer patch/Map019.txt
Gaijinizer patch/Map024.txt
Gaijinizer patch/Map027.txt
Gaijinizer patch/Map041.txt
Gaijinizer patch/Map042.txt
Gaijinizer patch/Map062.txt
Gaijinizer patch/Map070.txt
Gaijinizer patch/Map080.txt
Gaijinizer patch/Map085.txt
Gaijinizer patch/Map119.txt
Gaijinizer patch/Map120.txt
Gaijinizer patch/Map121.txt
Gaijinizer patch/Map122.txt
Gaijinizer patch/Map215.txt
Gaijinizer patch/Map216.txt

All of the My Room engagement dialogues (the gifting of the ring) should now be done or checked. All of the My Room files that don't have additional EX or DLC dialogue should also be 100% complete with no MTLed.

My room engagement dialogues

---

Gaijinizer patch/Map216.txt
Gaijinizer patch/Troops.txt

and exactly 1 line from Daji's My Room

Bronze Box dialogue

---

Gaijinizer patch/Map054.txt
Gaijinizer patch/Map398.txt
Gaijinizer patch/Map399.txt
Gaijinizer patch/Map401.txt
Gaijinizer patch/Map402.txt
Gaijinizer patch/Map403.txt
Gaijinizer patch/Map404.txt
Gaijinizer patch/Skills.txt
Gaijinizer patch/Troops.txt

The following is included in this PR
- Initial dialogue with Titania
- Initial dialogue after finding Sphinx
- Dialogues with Sphinx, Puck, and the random fairy in the square
- Ena and Mai's second confrontation
- Accepting life with Ena and Mai scene
- Post-battle dialogue with Mai
- Cheshire dialogue while shrunk
- Pre and post-battle dialogue with Ena
- The dialogue with Cheshire immediately after being shrunk
Not included in this PR
- Ena's and Mai's battle dialogues
- Ena's and Mai's loss scenes
- Optional dialogue with Cheshire after being unshrunk (for next PR)

Post forest

---

Gaijinizer patch/CommonEvents_654.txt
Gaijinizer patch/Map025.txt
Gaijinizer patch/Skills.txt

CE_654 was completely changed in v7.12, and I fixed a few remaining typos.

Ex3 images and final changes

---

Gaijinizer patch/CommonEvents_130.txt
Gaijinizer patch/CommonEvents_131.txt
Gaijinizer patch/CommonEvents_132.txt
Gaijinizer patch/CommonEvents_595.txt
Gaijinizer patch/CommonEvents_624.txt
Gaijinizer patch/CommonEvents_625.txt
Gaijinizer patch/Map323.txt
Gaijinizer patch/Map324.txt
Gaijinizer patch/Map327.txt
Gaijinizer patch/Map329.txt
Gaijinizer patch/Map344.txt
Gaijinizer patch/Map345.txt
Gaijinizer patch/Map346.txt
Gaijinizer patch/Map347.txt
Gaijinizer patch/Map348.txt
Gaijinizer patch/Map349.txt
Gaijinizer patch/Troops.txt

The opening sequence and first battle of EX2, including:
- Dialogue with the three girls before entering EX2
- Meeting Mormo
- Dressing room dialogue and events
- Mormo's battle and associated loss scenes
- Miscellaneous text (e.g. save station, etc)
- Events after defeating Mormo up until Kazuya is de-aged

EX2 opening

---

Gaijinizer patch/Enemies.txt
Gaijinizer patch/Map002.txt
Gaijinizer patch/Map344.txt
Gaijinizer patch/Map360.txt
Gaijinizer patch/Map361.txt
Gaijinizer patch/Map362.txt
Gaijinizer patch/Map363.txt
Gaijinizer patch/Map364.txt
Gaijinizer patch/Troops.txt

- Mormo and Hecate's dialogue
- Corrupted Mormo encounter in her dressing room
- Dialogue after defeating corrupted Mormo

EX2 - Corrupted Mormo

---

Gaijinizer patch/Actors.txt
Gaijinizer patch/Enemies.txt
Gaijinizer patch/Map002.txt
Gaijinizer patch/Map019.txt
Gaijinizer patch/Map024.txt
Gaijinizer patch/Map027.txt
Gaijinizer patch/Map041.txt
Gaijinizer patch/Map042.txt
Gaijinizer patch/Map062.txt
Gaijinizer patch/Map070.txt
Gaijinizer patch/Map075.txt
Gaijinizer patch/Map080.txt
Gaijinizer patch/Map085.txt
Gaijinizer patch/Map119.txt
Gaijinizer patch/Map120.txt
Gaijinizer patch/Map121.txt
Gaijinizer patch/Map122.txt
Gaijinizer patch/Map193.txt
Gaijinizer patch/Map215.txt
Gaijinizer patch/Map216.txt
Gaijinizer patch/Map217.txt
Gaijinizer patch/Map218.txt
Gaijinizer patch/Map254.txt
Gaijinizer patch/Map343.txt
Gaijinizer patch/Troops.txt
Patch/Gaijinizer/Eval/Gaijinizer.rb

A few things in this one:
- Update Gaijinizer, which fixes a bunch of NamePop things...
- Add to translations that the NamePop change fixes (Mementos, Main Menu, Friendship printouts in My Room, doors)
- Add translation for Anaon corruption reduction.

Gaijinizer Update

---

Gaijinizer patch/Armors.txt
Gaijinizer patch/CommonEvents_760.txt
Gaijinizer patch/CommonEvents_806.txt
Gaijinizer patch/Map402.txt
Gaijinizer patch/Scripts.txt
Gaijinizer patch/Skills.txt
Gaijinizer patch/Troops.txt
Gaijinizer patch/Weapons.txt

Fix global files with new text.
Map002 isn't in this one because it's a pain and not as priority. I'll add it later.

V8.04 backend

---

Gaijinizer patch/CommonEvents_175.txt
Gaijinizer patch/Enemies.txt

EX1 enemy (and Twins) compendium entries + Tengu Prince gift dialogue

Ex1 compendium+gift

---

Gaijinizer patch/Enemies.txt
Gaijinizer patch/Map002.txt
Gaijinizer patch/Map062.txt
Gaijinizer patch/Map085.txt
Gaijinizer patch/Map119.txt
Gaijinizer patch/MapInfos.txt
Gaijinizer patch/Skills.txt
Gaijinizer patch/States.txt
Gaijinizer patch/System.txt

Make some fixes for the patch to work on v8.06, and finally fix up Map002 for release. This takes a bit of Ron's work from his EX4 PRs.

V8.06fixes

---

Gaijinizer patch/CommonEvents_712.txt
Gaijinizer patch/CommonEvents_751.txt
Gaijinizer patch/CommonEvents_752.txt
Gaijinizer patch/CommonEvents_770.txt
Gaijinizer patch/CommonEvents_789.txt
Gaijinizer patch/CommonEvents_796.txt
Gaijinizer patch/CommonEvents_797.txt
Gaijinizer patch/CommonEvents_800.txt
Gaijinizer patch/CommonEvents_801.txt
Gaijinizer patch/Map002.txt
Gaijinizer patch/Skills.txt
Gaijinizer patch/Troops.txt

This PR contains the following
- Chimera Beast battle dialogue
- Evaluation for Chimera Beast
- Chimera Beast solo loss scene
- Chimera Beast group loss scene
- Chimera Beast scene selection in main menu
- Some battle text for Luka's status
- High Lamia's second loss scene
- High Lamia's scene selection in main menu
- Vasilica's loss scene
- Vasilica's loss scene selection from main menu
- Some skill translation fix-ups
- Two loss scene skills

EX4 Scenes - 3

---

Gaijinizer patch/Armors.txt
Gaijinizer patch/CommonEvents_735.txt
Gaijinizer patch/CommonEvents_783.txt
Gaijinizer patch/CommonEvents_784.txt
Gaijinizer patch/CommonEvents_798.txt
Gaijinizer patch/CommonEvents_799.txt
Gaijinizer patch/CommonEvents_802.txt
Gaijinizer patch/CommonEvents_806.txt
Gaijinizer patch/CommonEvents_810.txt
Gaijinizer patch/CommonEvents_816.txt
Gaijinizer patch/Enemies.txt
Gaijinizer patch/Map002.txt
Gaijinizer patch/Map193.txt
Gaijinizer patch/Skills.txt
Gaijinizer patch/Troops.txt

This PR contains the following:
* Ubbo-Sathla loss scene
* Ubbo-Sathla loss scene selection menu
* Red Beelzebub's loss scene and her scene epilogue
* Some missed battle skills for Abaddon
* Compendium entries for EX4
* Black Dog's platinum box
* High Slug's platinum box
* Chimera Beast's platinum box
* Vascilica's platinum box
* Abaddon's loss scene
* New platinum box descriptions
* Abaddon's loss scene view menu

EX4 Scenes - 4
